### ISSUE TITLE
Argentina Mobile and SMS

### ISSUE THREAD

**Issue by allendav** [AfterShip/node-phone#18]
We're using the library to validate SMS phone numbers, and Argentinian SMS has a wrinkle - it doesn't support the leading 9, per http://en.wikipedia.org/wiki/Telephone_numbers_in_Argentina#Inbound_SMS

Also, it looks like Argentinian numbers can be 6, 7 or 8 digits long.  I'm curious about the 10 in the code:

`country_code: "54", country_name: "Argentina", mobile_begin_with: ["9"], phone_number_lengths: [10]`

Would you entertain a pull request that removes the mobile_begin_with 9 requirement and replaces the 10 with 6, 7, 8, 9 (to cover whether or not the leading 9 is present).  Or is there a better approach to fix this?

**Comment by cilindrox** [comment]
:+1: struggling with the same problem

**Comment by mypark** [comment]
I'm having the same issue as well

**Comment by brunocascio** [comment]
+1
