### ISSUE TITLE
Update some +1 areas

### ISSUE THREAD

**Issue by theoephraim** [AfterShip/node-phone#25]
by no means exhaustive, but some "mobile_begin_with" rules I found in numbers already in my database for numbers with the country code +1 and 10 digit numbers
- 340 -- virgin islands
- 787, 939 -- puerto rico
- 876 -- jamaica
- 242 -- bahamas

**Comment by teddychan** [comment]
May I know do you have any reference to check if those prefix are mobile?
It seems like it is just an area code, like `340`

**Comment by theoephraim** [comment]
Only what I see in my database from users.

I do see that "1340" is the prefix listed on twilio for sending messages to the US virgin islands.

**Comment by teddychan** [comment]
787, 939 -- puerto rico i verified and merged the pull request.
now checking at others

**Comment by teddychan** [comment]
update with the suggestion:

https://github.com/AfterShip/node-phone/commit/22e20c09591aa3201937e698fd8cf63d2ddc0073
