### ISSUE TITLE
Parsing "+17878787" as "AIA"?

### ISSUE THREAD

**Issue by DomKM** [AfterShip/node-phone#31]
```js
phone("+17878787") // ["+17878787", "AIA"]
```

It looks like this shouldn't happen because [Anguilla numbers begin with "+1 264"](https://en.wikipedia.org/wiki/List_of_country_calling_codes#Zone_1:_North_American_Numbering_Plan_Area). Is this a bug?

**Comment by teddychan** [comment]
+1 787 / 939  Puerto Rico
I also double check and fix the following location


+1  United States, including United States territories:
  +1 340  United States Virgin Islands
  +1 670  Northern Mariana Islands
  +1 671  Guam
  +1 684  American Samoa
  +1 787 / 939  Puerto Rico

+1 Many, but not all, Caribbean nations and some Caribbean Dutch and British Overseas Territories:
  +1 242  Bahamas
  +1 246  Barbados
  +1 264  Anguilla
  +1 268  Antigua and Barbuda
  +1 284  British Virgin Islands
  +1 345  Cayman Islands
  +1 441  Bermuda
  +1 473  Grenada
  +1 649  Turks and Caicos Islands
  +1 664  Montserrat
  +1 721  Sint Maarten <-- not found
  +1 758  Saint Lucia
  +1 767  Dominica
  +1 784  Saint Vincent and the Grenadines
  +1 809 / 829 / 849  Dominican Republic
  +1 868  Trinidad and Tobago
  +1 869  Saint Kitts and Nevis
  +1 876  Jamaica

**Comment by teddychan** [comment]
Notice that phone("+17878787") should be an invalid phone number (no matter mobile or land)
as `+1 787 XXXX YYY` total should be 11 digits.
